web:
    image: nginx:latest
    ports:
        - "80:80"
    volumes:
        - ./conf/vhost.conf:/etc/nginx/sites-enabled/vhost.conf:ro
        - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./src:/var/www/docker:ro
    volumes_from:
        - php
    links:
        - php
php:
  image: aevumdecessus/php-fpm-mysql
  volumes:
      - ./src:/var/www/docker:ro
      - ./conf/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro
  links:
      - db
db:
    image: mariadb:latest
    volumes_from:
        - data-mariadb-openbiblio
    environment:
        - MYSQL_ROOT_PASSWORD=y5cbLFd3Z7zskRGwXSdScHqm
        - MYSQL_DATABASE=openbiblio
        - MYSQL_USER=openbiblio
        - MYSQL_PASSWORD=ltK5mbFuqjLI3Rk6Ts2wwE3A
